const featuredItems = [
  {
    id: 1,
    title: "Mens Casual Slim Fit",
    price: 15.99,
    description: "",
    filterCategory: "women",
    category: "men's clothing",
    image: "/images/products/uploaded/dummary_four.png",
    isFeatured: true,
  },
  {
    id: 2,
    title: "Women Sweat Shirt",
    price: 39.99,
    description: "",
    filterCategory: "women",
    category: "women's clothing",
    image: "/images/products/uploaded/dummy_one.png",
    isFeatured: true,
  },
  {
    id: 3,
    title: "Men Neck T-shirt",
    price: 33.99,
    description: "",
    filterCategory: "men",
    category: "men's clothing",
    image: "/images/products/uploaded/neck_tshirt.png",
    isFeatured: true,
  },
  {
    id: 4,
    title: "DANVOUY Womens Hoodie",
    price: 12.99,
    description: "",
    filterCategory: "women",
    category: "women's clothing",
    image: "/images/products/uploaded/dummy_two.png",
    isFeatured: true,
  },
  {
    id: 5,
    title: "Men Plain T-shirt",
    price: 13.99,
    description: "",
    filterCategory: "men",
    category: "men's clothing",
    image: "/images/products/uploaded/white_tshirt.png",
    isFeatured: true,
  },
  {
    id: 6,
    title: "Women Plain T-shirt",
    price: 13.99,
    description: "",
    filterCategory: "women",
    category: "men's clothing",
    image: "/images/products/ladies_tshirt.png",
    isFeatured: true,
  },
];

export default featuredItems;
